### PR TITLE
Chapters are included with wrong case

### PR DESCRIPTION
**Pull request by cdlm**
E.g. `\input{preface}` but the file is named `Preface.tex`
That's means it probably never compiled on proper filesystems (and will be a pain if you want to build it on the CI infra)

I'd prefer to rename the files to a consistent case convention rather than change the `\input` statements, but you might have to do a clean checkout to avoid problems… what do you think ?

### CODE REVIEW

**Comment by Ducasse** [comment]
Yes I saw I’m fixing that…. as soon as latex is installed.

**Comment by cdlm** [comment]
I can do it, just tell me which way you prefer

**Comment by Ducasse** [comment]
Can you check because I did it.

Stef

**Comment by cdlm** [comment]
Can't see where. Did you commit?
In fact I'm not sure git will correctly pick up case renamings if you're working on a case-insensitive FS…

**Pull request merged**
